### ISSUE TITLE
General clean-up

### ISSUE THREAD

**Issue by matsen** [matsengrp/lcfit#5]
Getting ready for submission, 

* is the README up to date? 
* is anyone using the clang complete and syntastic files
* are there old bits that aren't up to date, such as the R interface?

**Comment by bcclaywell** [comment]
* The README is mostly up to date, though the section on running the sims could probably use a pass-through.
* I'm not using the clang or syntastic files, no, so they can probably go.
* The R interface is definitely not up to date and is probably very broken.

Some more points:

* The simulations could also use some work; as I mentioned in chat they were written before lcfit2 and lcfit4 were unified.
* The Doxygen documentation could probably use some updating as well.

**Comment by bcclaywell** [comment]
Most of these issues were addressed a while ago, closing.
